version: '3'

services:

  rentalbikescript:
    image: trigynravishankar/profirator:rentalbike
    environment:
      - PYTHONUNBUFFERED=1
      - orionUri=http://192.168.16.112:1026/
    volumes:
      - "../config/rentalbike/rentalbike.ini:/rentalbike.ini"